version: '3.4'
services:
  api:
    image: 'michelmdes/cliente-api:latest'
    build:
      context: .
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234

  db:
    image: 'michelmdes/cliente-api-db-pgsql:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234